# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package' 
    
- task: SendEmail@1
  inputs:
    To: 'domheydon1@gmail.com'
    From: 'asdemailuts@gmail.com'
    Subject: 'Test'
    Body: 'Test'
    BodyAsHtml: false
    AddAttachment: true
    Attachment: '/home/vsts/work/1/s/target/ASD_Incident_Reporting_System-1.0-SNAPSHOT.war'
    SmtpServer: 'smtp.gmail.com'
    SmtpUsername: 'asdemailuts@gmail.com'
    SmtpPassword: 'asdEmailUTS123!'